name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  #schedule:
  #- cron: '*/5 * * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker pull apache/flink:1.18.1-scala_2.12
        docker login REGISTRY_SERVER
        docker push IMAGE_TAG
