name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag registry.cn-beijing.aliyuncs.com/yican/flink:1.18
        docker login --username=yihaiyang@manwei --password=manwei@123 registry.cn-beijing.aliyuncs.com
        docker push registry.cn-beijing.aliyuncs.com/yican/flink:1.18
